# wechat rules
windowrule   = workspace 10, class:^(wechat)$
windowrule = float, class:^(wechat)$,title:^(预览)$
windowrule = size 50% 50%, class:^(wechat)$,title:^(预览)$
windowrulev2 = noblur , class:^(wechat)$,title:^(wechat)$
windowrulev2 = bordersize 0, class:^(wechat)$,title:^(wechat)$
windowrulev2 = noshadow, class:^(wechat)$,title:^(wechat)$
# fierfox
windowrule = workspace 2, class:^(firefox)$
windowrule = float, class:^(firefox)$,title:^(Library)$
windowrule = size 50% 50%, class:^(firefox)$,title:^(Library)$

# Float Alacritty
windowrulev2 = noblur, initialTitle:^(FloatTTY)$
windowrule = float, initialTitle:^(FloatTTY)$
windowrulev2 = noshadow, initialTitle:^(FloatTTY)$

# Rofi
#windowrule = pin,class:^(Rofi)$
windowrule = stayfocused,class:^(Rofi)$

# v2ray
windowrule = workspace special:proxy silent, class:^(v2rayN)$

# Files org.gnome.Nautilus 正在加载…
windowrule = float, class:^(org.gnome.Nautilus)$
windowrule = float, class:^(xdg-desktop-portal-gtk)$
windowrule = size 50% 50%, class:^(org.gnome.Nautilus)$
windowrule = size 50% 50%, class:^(xdg-desktop-portal-gtk)$
windowrule = float, class:^(org.gnome.NautilusPreviewer)$
windowrule = size 50% -1%, class:^(org.gnome.NautilusPreviewer)$
#windowrule = size 50% 50%, class:^(org.gnome.Nautilus)$,initialTitle:^(正在加载…)$
#windowrule = float, class:^(org.gnome.Nautilus)$,initialTitle:^(Loading…)$
#windowrule = size 50% 50%, class:^(org.gnome.Nautilus)$,initialTitle:^(Loading…)$

# Steam
windowrule = workspace 9 silent, class:^(steam)$
windowrule = float, class:^(steam)$,title:^(Friends List)$

# feh borderless image viewer
windowrulev2 = noblur, class:^(feh)$
#windowrulev2 = noshadow, class:^(feh)$
windowrule = float, class:^(feh)$
windowrule = pin, class:^(feh)$
windowrule = opacity 0.5 override, title:^(OPT)$


windowrulev2 = opacity 1 override, class:^(Typora)$
windowrule = opacity 1 override, class:^(obsidian)$
windowrule = opacity 1 override, class:^(firefox)$
windowrule = opacity 1 override, class:^(Zotero)$
windowrule = opacity 1 override, class:^(code-oss)$
windowrule = opacity 1 override, class:^(ONLYOFFICE)$
windowrule = opacity 1 override, class:^(matplotlib)$
windowrule = opacity 1 override, class:^(texstudio)$
windowrule = opacity 1 override, class:^(Waydroid)$
windowrule = workspace 9, class:^(com.obsproject.Studio)$

windowrule = float, class:(python3)
windowrule = size 40% 40%, class:(python3)
           
