windowrule = no_blur on, match:content 0
# wechat rules
windowrule   = workspace 10, match:class wechat 
windowrule = float true, match:class wechat,match:title 预览
windowrule = size 50% 50%, match:class wechat,match:title 预览
windowrule = no_blur on, match:class wechat,match:title wechat
windowrule = border_size 0, match:class wechat,match:title wechat
windowrule = no_shadow on, match:class wechat,match:title wechat
# fierfox
windowrule = workspace 2, match:class firefox
windowrule = float on, match:class firefox, match:title Library
windowrule = size 0.5*monitor_w 0.5*monitor_h, match:class firefox,match:title Library
windowrule = scrolling_width 1, match:class firefox

# Alacritty
windowrule = no_blur off, match:class Alacritty

# Float Alacritty
windowrule = no_blur on, match:initial_title FloatTTY
windowrule = float on, match:initial_title FloatTTY
windowrule = no_shadow on, match:initial_title FloatTTY

# Rofi
#windowrule = pin,match:class Rofi
windowrule = stay_focused on,match:class Rofi
windowrule = no_blur off,match:class Rofi

# v2ray
windowrule = workspace special:proxy silent, match:class v2rayN

# Files org.gnome.Nautilus 正在加载…
windowrule = float true, match:class org.gnome.Nautilus
windowrule = float true, match:class xdg-desktop-portal-gtk
windowrule = size 50% 50%, match:class org.gnome.Nautilus
windowrule = size 50% 50%, match:class xdg-desktop-portal-gtk
windowrule = float true, match:class org.gnome.NautilusPreviewer
windowrule = size 50% -1%, match:class org.gnome.NautilusPreviewer
#windowrule = size 50% 50%, match:class org.gnome.Nautilus,match:initial_title 正在加载…
#windowrule = float, match:class org.gnome.Nautilus,match:initial_title Loading…
#windowrule = size 50% 50%, match:class org.gnome.Nautilus,match:initial_title Loading…

# Steam
windowrule = workspace 9 silent, match:class steam
windowrule = float true, match:class steam,match:title Friends List
#windowrule = fullscreen on, match:class gamescope
#windowrule = workspace special:game, match:class gamescope

# feh borderless image viewer
windowrule = no_blur on, match:class feh
#windowrule = noshadow, match:class feh
windowrule = float on, match:class feh
windowrule = pin on, match:class feh
windowrule = opacity 0.5 override, match:title OPT

# wemeet
windowrule = pin on, match:title wemeetapp
windowrule = no_blur on, match:title wemeetapp
windowrule = no_shadow on, match:title wemeetapp
windowrule = border_size 0, match:title wemeetapp

# Typora
windowrule = opacity 1 override, match:class Typora
windowrule = float on, match:class xdg-desktop-portal-gtk
windowrule = size 0.5*monitor_w 0.5*monitor_h, match:class xdg-desktop-portal-gtk

# nvim 

windowrule = opacity 1 override, match:class firefox
windowrule = opacity 1 override, match:class Zotero
windowrule = opacity 1 override, match:class matplotlib
windowrule = opacity 1 override, match:class texstudio
windowrule = workspace 9, match:class com.obsproject.Studio

windowrule = float true, match:class python3
windowrule = size 40% 40%, match:class python3
#windowrule = opacity 0.4 override, match:class python3




layerrule = blur on, match:namespace gtk-layer-shell
layerrule = ignore_alpha 0, match:namespace gtk-layer-shell
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0, match:namespace waybar

           
