# wechat rules
windowrulev2 = noblur , class:^(wechat)$,title:^(wechat)$
windowrulev2 = bordersize 0, class:^(wechat)$,title:^(wechat)$
windowrulev2 = noshadow, class:^(wechat)$,title:^(wechat)$
# fierfox
windowrule = workspace 2, class:^(firefox)$

# Float Alacritty
windowrulev2 = noblur, initialTitle:^(FloatTTY)$
windowrulev2 = noshadow, initialTitle:^(FloatTTY)$

# Rofi
windowrule = pin,class:^(Rofi)$

windowrulev2 = opacity 1 override, class:^(Typora)$
windowrule = opacity 1 override, class:^(obsidian)$
windowrule = opacity 1 override, class:^(firefox)$
windowrule = opacity 1 override, class:^(Zotero)$
windowrule = opacity 1 override, class:^(code-oss)$
windowrule = opacity 1 override, class:^(ONLYOFFICE)$
windowrule = opacity 1 override, class:^(matplotlib)$
windowrule = opacity 1 override, class:^(texstudio)$
windowrule = workspace 8, class:^(Waydroid)$
windowrule = opacity 1 override, class:^(Waydroid)$
windowrule = workspace 9, class:^(com.obsproject.Studio)$

windowrule = float, class:(python3)
windowrule = size 40% 40%, class:(python3)
           
